### ISSUE TITLE
Permission change needed for API testing

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-frontend#125]
The error below occurred when I ran run_api_test.py on the tst server. Add write permission for group/others to file:  /data/shared/glygen//logs/test_summary_glycan_mode_2.csv

```
[karinamartinez@glygen-vm-tst tests]$ python3 run_api_test.py -m 2 -g glycan
Traceback (most recent call last):
  File "run_api_test.py", line 89, in run_exhaustive
    FW = open(summary_file, "w")
PermissionError: [Errno 13] Permission denied: '/data/shared/glygen//logs/test_summary_glycan_mode_2.csv'

[karinamartinez@glygen-vm-tst tests]$ ls -l /data/shared/glygen//logs/
total 15
-rw-r--r--. 1 rykahsay glygen 823 Nov 30 16:17 failure_log_motif_detail.GGM.000058.json
-rw-r--r--. 1 rykahsay glygen 217 Nov 30 16:08 test_summary_glycan_mode_1.csv
-rw-r--r--. 1 rykahsay glygen  56 Nov 30 16:14 test_summary_motif_mode_1.csv
-rw-r--r--. 1 rykahsay glygen 266 Nov 30 16:17 test_summary_motif_mode_2.csv
-rw-r--r--. 1 rykahsay glygen 199 Nov 30 16:08 test_summary_protein_mode_1.csv
-rw-r--r--. 1 rykahsay glygen 254 Nov 23 11:08 test_summary_protein_mode_2.csv
```

**Comment by rykahsay** [comment]
@kmartinez834 @jeet-vora -- I have tried to correct it, please use git pull (or clone it again) and try.

**Comment by kmartinez834** [comment]
After git pull, I received the following error:

```
[karinamartinez@glygen-vm-tst tests]$ python3 run_api_test.py -m 2 -g glycan
Traceback (most recent call last):
  File "run_api_test.py", line 282, in <module>
    main()
  File "run_api_test.py", line 270, in main
    run_exhaustive(api_grp)
  File "run_api_test.py", line 69, in run_exhaustive
    data_version = info_obj["initobj"]["dataversion"]
KeyError: 'initobj'
```

**Comment by rykahsay** [comment]
Please give it a try now  ...

**Comment by kmartinez834** [comment]
Getting the following error:
```
[karinamartinez@glygen-vm-tst tests]$ python3 run_api_test.py -m 2 -g glycan
Traceback (most recent call last):
  File "run_api_test.py", line 88, in run_exhaustive
    FW = open(summary_file, "w")
PermissionError: [Errno 13] Permission denied: '/data/shared/glygen//logs/karinamartinez_test_summary_glycan_mode_2.csv'
```

**Comment by rykahsay** [comment]
Try now

**Comment by kmartinez834** [comment]
@rykahsay it worked.  Took about an hour to run.  There are 34620 success rows, and 35 failed rows. I am iterating the glycan schema before I hand off to Rene and Sujeet.
